### ISSUE TITLE
Switch to a Spring Boot standalone application with runnable fat JAR

### ISSUE THREAD

**Issue by tkrille** [osiam/auth-server#39]
This is the umbrella issue for the transition of this component to a Spring Boot standalone application with an executable fat JAR. See also osiam/osiam#5 for the initial reasons and discussion.

Tasks that have to be done:
- [x] Change Hibernate naming strategy (#13 / PR: #33)
- [x] Switch from xml to java configuration (#23 / PR: #50)
- [x] Introduce Spring Boot, but keep WAR deployment (#24 / PR: #50)
- [ ] Switch to YAML configration (#40)
- [ ] Switch to standalone application (#25)

Please, maintain this list, if you add new issues or close existing ones.

**Comment by dacrome** [comment]
Moved to https://github.com/osiam/osiam/issues/69
